/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type GameGenre = { 'sciFi' : null } |
  { 'mystery' : null } |
  { 'horror' : null } |
  { 'fantasy' : null };
export type GameId = bigint;
export interface StableGameSessionDTO {
  'turns' : Array<TurnDTO>,
  'genre' : GameGenre,
}
export interface TurnDTO { 'playerAction' : string, 'storyText' : string }
export interface TurnInputDTO { 'action' : string, 'genre' : GameGenre }
export interface _SERVICE {
  'createGame' : ActorMethod<[GameGenre], bigint>,
  'deleteGame' : ActorMethod<[bigint], boolean>,
  'getGame' : ActorMethod<[bigint], [] | [StableGameSessionDTO]>,
  'listGames' : ActorMethod<[], Array<[GameId, StableGameSessionDTO]>>,
  'submitTurn' : ActorMethod<[bigint, TurnInputDTO], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];