/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameGenre = IDL.Variant({
  'sciFi' : IDL.Null,
  'mystery' : IDL.Null,
  'horror' : IDL.Null,
  'fantasy' : IDL.Null,
});
export const TurnDTO = IDL.Record({
  'playerAction' : IDL.Text,
  'storyText' : IDL.Text,
});
export const StableGameSessionDTO = IDL.Record({
  'turns' : IDL.Vec(TurnDTO),
  'genre' : GameGenre,
});
export const GameId = IDL.Nat;
export const TurnInputDTO = IDL.Record({
  'action' : IDL.Text,
  'genre' : GameGenre,
});

export const idlService = IDL.Service({
  'createGame' : IDL.Func([GameGenre], [IDL.Nat], []),
  'deleteGame' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getGame' : IDL.Func([IDL.Nat], [IDL.Opt(StableGameSessionDTO)], []),
  'listGames' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(GameId, StableGameSessionDTO))],
      [],
    ),
  'submitTurn' : IDL.Func([IDL.Nat, TurnInputDTO], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameGenre = IDL.Variant({
    'sciFi' : IDL.Null,
    'mystery' : IDL.Null,
    'horror' : IDL.Null,
    'fantasy' : IDL.Null,
  });
  const TurnDTO = IDL.Record({
    'playerAction' : IDL.Text,
    'storyText' : IDL.Text,
  });
  const StableGameSessionDTO = IDL.Record({
    'turns' : IDL.Vec(TurnDTO),
    'genre' : GameGenre,
  });
  const GameId = IDL.Nat;
  const TurnInputDTO = IDL.Record({ 'action' : IDL.Text, 'genre' : GameGenre });
  
  return IDL.Service({
    'createGame' : IDL.Func([GameGenre], [IDL.Nat], []),
    'deleteGame' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getGame' : IDL.Func([IDL.Nat], [IDL.Opt(StableGameSessionDTO)], []),
    'listGames' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(GameId, StableGameSessionDTO))],
        [],
      ),
    'submitTurn' : IDL.Func([IDL.Nat, TurnInputDTO], [], []),
  });
};

export const init = ({ IDL }) => { return []; };