/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TurnInputDTO {
    action: string;
    genre: GameGenre;
}
export interface StableGameSessionDTO {
    turns: Array<TurnDTO>;
    genre: GameGenre;
}
export type GameId = bigint;
export interface TurnDTO {
    playerAction: string;
    storyText: string;
}
export enum GameGenre {
    sciFi = "sciFi",
    mystery = "mystery",
    horror = "horror",
    fantasy = "fantasy"
}
export interface backendInterface {
    createGame(genre: GameGenre): Promise<bigint>;
    deleteGame(gameId: bigint): Promise<boolean>;
    getGame(gameId: bigint): Promise<StableGameSessionDTO | null>;
    listGames(): Promise<Array<[GameId, StableGameSessionDTO]>>;
    submitTurn(gameId: bigint, input: TurnInputDTO): Promise<void>;
}
import type { GameGenre as _GameGenre, GameId as _GameId, StableGameSessionDTO as _StableGameSessionDTO, TurnDTO as _TurnDTO, TurnInputDTO as _TurnInputDTO } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createGame(arg0: GameGenre): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGame(to_candid_GameGenre_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGame(to_candid_GameGenre_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteGame(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGame(arg0);
            return result;
        }
    }
    async getGame(arg0: bigint): Promise<StableGameSessionDTO | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGame(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGame(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async listGames(): Promise<Array<[GameId, StableGameSessionDTO]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGames();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGames();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitTurn(arg0: bigint, arg1: TurnInputDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTurn(arg0, to_candid_TurnInputDTO_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTurn(arg0, to_candid_TurnInputDTO_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_GameGenre_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameGenre): GameGenre {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_StableGameSessionDTO_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StableGameSessionDTO): StableGameSessionDTO {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StableGameSessionDTO]): StableGameSessionDTO | null {
    return value.length === 0 ? null : from_candid_StableGameSessionDTO_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    turns: Array<_TurnDTO>;
    genre: _GameGenre;
}): {
    turns: Array<TurnDTO>;
    genre: GameGenre;
} {
    return {
        turns: value.turns,
        genre: from_candid_GameGenre_n6(_uploadFile, _downloadFile, value.genre)
    };
}
function from_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_GameId, _StableGameSessionDTO]): [GameId, StableGameSessionDTO] {
    return [
        value[0],
        from_candid_StableGameSessionDTO_n4(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sciFi: null;
} | {
    mystery: null;
} | {
    horror: null;
} | {
    fantasy: null;
}): GameGenre {
    return "sciFi" in value ? GameGenre.sciFi : "mystery" in value ? GameGenre.mystery : "horror" in value ? GameGenre.horror : "fantasy" in value ? GameGenre.fantasy : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_GameId, _StableGameSessionDTO]>): Array<[GameId, StableGameSessionDTO]> {
    return value.map((x)=>from_candid_tuple_n9(_uploadFile, _downloadFile, x));
}
function to_candid_GameGenre_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameGenre): _GameGenre {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TurnInputDTO_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TurnInputDTO): _TurnInputDTO {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: string;
    genre: GameGenre;
}): {
    action: string;
    genre: _GameGenre;
} {
    return {
        action: value.action,
        genre: to_candid_GameGenre_n1(_uploadFile, _downloadFile, value.genre)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameGenre): {
    sciFi: null;
} | {
    mystery: null;
} | {
    horror: null;
} | {
    fantasy: null;
} {
    return value == GameGenre.sciFi ? {
        sciFi: null
    } : value == GameGenre.mystery ? {
        mystery: null
    } : value == GameGenre.horror ? {
        horror: null
    } : value == GameGenre.fantasy ? {
        fantasy: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
